<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Message extends Model
{
    protected $table = 'messages';

    protected $fillable = ['from_user_id','to_user_id','body','dialog_id'];

    public function fromUser()
    {
        return $this->belongsTo(User::class,'from_user_id');
    }

    public function toUser()
    {
        return $this->belongsTo(User::class,'to_user_id');
    }

    /**
     * 标记未读信件为已读
     */
    public function markAsRead()
    {
        if(is_null($this->read_at)) {
            $this->forceFill(['read_at' => $this->freshTimestamp(),'has_read' => 'T'])->save();
        }
    }

    public function newCollection(array $models = [])
    {
        return new MessageCollection($models); // TODO: Change the autogenerated stub
    }

    public function read()
    {
      return $this->has_read == 'T';
    }

    public function unread()
    {
        return $this->has_read == 'F';
    }

    public function shouldAddReadClass()
    {
            if( Auth::id() === $this->from_user_id) {
                return false;
            }
            return $this->unread();

    }

}
